name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          rm -rf ~/.cache/pip
          pip install --upgrade pip
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
          pip show test_utils
      
      - name: Desactivar Selenium Manager
        run: echo "SE_MANAGER=0" >> $GITHUB_ENV
      
      - name: Instalar Google Chrome y Chromedriver
        run: |
          echo "⏳ Verificando si Google Chrome ya está instalado..."
          if command -v google-chrome &> /dev/null; then
            echo "✅ Google Chrome ya está instalado: $(google-chrome --version)"
          else
            echo "📥 Instalando Google Chrome..."
            set +e  # 🔴 Permitir errores temporalmente
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            set -e  # ✅ Volver a activar la detención de errores
          fi
      
          # Obtener la versión de Chrome instalada
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "✅ Chrome instalado en versión: $CHROME_VERSION"
      
          # Instalar Chromedriver correspondiente
          echo "⏳ Descargando Chromedriver..."
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
      
          echo "✅ Chromedriver instalado en: $(which chromedriver)"
      

      - name: Verificar instalación de Chromedriver
        run: chromedriver --version

      - uses: actions/checkout@v4
        if: success() || failure()
      - run: |
          pytest tests -v -s -m Smoke
