name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          rm -rf ~/.cache/pip
          pip install --upgrade pip
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
          pip show test_utils

      - uses: actions/checkout@v4
        if: success() || failure()
      - run: |
          pytest tests -v -s -m Smoke --headless --start-maximized --browser_type Firefox --junitxml=test-results/firefox_report.xml
          pytest tests -v -s -m Smoke --headless --start-maximized --browser_type Chrome --junitxml=test-results/chrome_report.xml
          pytest tests -v -s -m Smoke --headless --start-maximized --browser_type Edge --junitxml=test-results/edge_report.xml
      
      # - name: Add test report to summary
      #   run: |
      #     echo "## Test Report" >> $GITHUB_STEP_SUMMARY
      #     echo "" >> $GITHUB_STEP_SUMMARY
      #     echo "[Download Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
