name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          rm -rf ~/.cache/pip
          pip install --upgrade pip
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
          pip show test_utils
      
      - name: Desactivar Selenium Manager
        run: echo "SE_MANAGER=0" >> $GITHUB_ENV
      
      - name: Instalar Chromedriver
        run: |
          echo "⏳ Verificando si Chromedriver ya está instalado..."
          if command -v chromedriver &> /dev/null; then
            echo "✅ Chromedriver ya está instalado: $(chromedriver --version)"
          else
            echo "📥 Descargando la versión de Chromedriver compatible con Chrome $CHROME_VERSION..."
            
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
            
            if [ -z "$CHROMEDRIVER_VERSION" ]; then
              echo "⚠️ No se pudo obtener la versión de Chromedriver. Usando la última versión conocida."
              CHROMEDRIVER_VERSION="133.0.6943.98"  # Última versión conocida de Chromedriver
            fi
      
            echo "📥 Descargando Chromedriver versión: $CHROMEDRIVER_VERSION..."
            wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" || {
              echo "❌ Error al descargar Chromedriver. Reintentando con la última versión estable."
              wget -q "https://chromedriver.storage.googleapis.com/133.0.6943.98/chromedriver_linux64.zip"
            }
      
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver
      
            echo "✅ Chromedriver instalado en: $(which chromedriver)"
          fi
      
      

      - name: Verificar instalación de Chromedriver
        run: chromedriver --version

      - uses: actions/checkout@v4
        if: success() || failure()
      - run: |
          pytest tests -v -s -m Smoke
