name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          rm -rf ~/.cache/pip
          pip install --upgrade pip
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
          pip show test_utils
      
      - name: Desactivar Selenium Manager
        run: echo "SE_MANAGER=0" >> $GITHUB_ENV
      
      - name: Instalar Google Chrome y Chromedriver
        run: |
          set -e  # 🔴 Detiene el script si hay un error
          sudo apt-get update || echo "⚠️ Warning: Error en apt-get update"
          sudo apt-get install -y google-chrome-stable || echo "⚠️ Warning: Chrome ya está instalado"

          # Verificar versión de Chrome instalada
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "✅ Chrome instalado en versión: $CHROME_VERSION"

          # Descargar e instalar el `chromedriver` correspondiente
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          echo "✅ Chromedriver instalado en: $(which chromedriver)"


      - name: Verificar instalación de Chromedriver
        run: chromedriver --version

      - uses: actions/checkout@v4
        if: success() || failure()
      - run: |
          pytest tests -v -s -m Smoke
