name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/venv" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/venv/bin" >> $GITHUB_PATH
          source venv/bin/activate
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests -s -m Smoke --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --user-data-dir /tmp/edge-profile
