name: Pylint Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/venv" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/venv/bin" >> $GITHUB_PATH
          source venv/bin/activate
          pip install pylint

      - name: Run pylint
        run: |
          source venv/bin/activate
          pylint $(git ls-files '*.py')
